# Generated by Django 5.2.3 on 2025-06-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='comment',
        ),
    ]
